src/tutorial/customers/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^$', views.customers, name='customers'),
    url(r'^edit/(?P<pk>.*)$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>.*)$', views.delete, name='delete'),
    url(r'^view/(?P<pk>.*)$', views.customer, name='customer'),
]

src/tutorial/sales/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^$', views.sales, name='sales'),
    url(r'^edit/(?P<pk>.*)$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>.*)$', views.delete, name='delete'),
    url(r'^view/(?P<pk>.*)$', views.sale, name='sale'),
]

src/tutorial/tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),

    url(r'^app/products/', include('products.urls', namespace="products")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")),
    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/users/', include('users.urls', namespace="users")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

src/tutorial/users/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    
    url(r'^check-notification/$', views.check_notification, name='check_notification'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/delete/(?P<pk>.*)/$', views.delete_notification, name='delete_notification'),
    url(r'^delete-selected-notifications/$', views.delete_selected_notifications, name='delete_selected_notifications'),
    url(r'^notification/read/(?P<pk>.*)/$', views.read_notification, name='read_notification'),
    url(r'^read-selected-notifications/$', views.read_selected_notifications, name='read_selected_notifications'),
    
    url(r'^set-user-timezone/$', views.set_user_timezone, name='set_user_timezone'),
    
    
]

src/tutorial/templates/includes/form.html
{% for field in form %}
	{% if field.is_hidden %}
		{{ field }}
	{% elif field.field.is_checkbox %}
		<div class="form-group fg-line">
            <label for="{{ field.id_for_label }}">
            	{{ field.label }} 
            	{% if field.field.required %}
	        		<small class="star">*</small>
	        	{% endif %}
            </label>
            
            <br />
            
            <div class="toggle-switch m-t-10">
                <label class="ts-label"></label>
                {{ field }}
                <label class="ts-helper" for="ts1"></label>
            </div>
            
            {% if field.errors %}
            	<label class="error">{{ field.errors.as_text }}</label>
            {% endif %}
        </div>
 	
	{% else %}
		<div class="form-group fg-line">
            <label for="{{ field.id_for_label }}">
            	{{ field.label }}
            	{% if field.field.required %}
	        		<small class="star">*</small>
	        	{% endif %}
	        	
	        	{% if field.help_text %}
	        		<span data-original-title="Field Info" title="" data-content="{{ field.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                {% endif %}
            </label>
            {{ field }}
            
            {% if field.errors %}
            	<label class="error">{{ field.errors.as_text }}</label>
            {% endif %}
        </div>
	{% endif %}				    
{% endfor %}		

src/tutorial/templates/includes/menu.html
{% load static %}
<aside id="s-main-menu" class="sidebar">
    <div class="smm-header">
        <i class="zmdi zmdi-long-arrow-left" data-ma-action="sidebar-close"></i>
    </div>

    <ul class="smm-alerts">
        <li data-user-alert="sua-messages" data-ma-action="sidebar-open" data-ma-target="user-alerts">
            <i class="zmdi zmdi-email"></i>
        </li>
        <li class="p-relative" data-user-alert="sua-notifications" data-ma-action="sidebar-open" data-ma-target="user-alerts">
            <i class="zmdi zmdi-notifications"></i>
            <span class="notification-count palette-Red-500 bg">0</span>
        </li>
        <li data-user-alert="sua-tasks" data-ma-action="sidebar-open" data-ma-target="user-alerts">
            <i class="zmdi zmdi-view-list-alt"></i>
        </li>
    </ul>

    <ul class="main-menu">
        <li class="active">
            <a href="{% url 'app' %}"><i class="zmdi zmdi-home"></i>Dashboard</a>
        </li>
        <li class="sub-menu">
            <a href="" data-ma-action="submenu-toggle"><i class="zmdi zmdi-accounts-alt"></i>Customers</a>
            <ul>
                <li class="{% if active_menu == 'election_create_open' %}active{% endif %} m-b-5">
                        <a class="pull-left p-r-0" title="Customers" href="{% url 'customers:customers' %}">Customers</a>
                        <a title="Create Customer " href="{% url 'customers:create' %}">
                        <span class="pull-right glyphicon glyphicon-plus-sign"></span>
                        </a>
                    <div class="clearfix"></div>
                </li>
            </ul>
        </li>
        <li class="sub-menu">
            <a href="" data-ma-action="submenu-toggle"><i class="zmdi zmdi-storage"></i>Products</a>
            <ul>
                <li class="{% if active_menu == 'election_create_open' %}active{% endif %} m-b-5">
                        <a class="pull-left p-r-0" title="Products" href="#">Products</a>
                        <a title="Create Product " href="#">
                        <span class="pull-right glyphicon glyphicon-plus-sign"></span>
                        </a>
                    <div class="clearfix"></div>
                </li>
            </ul>
        </li>
        <li class="sub-menu">
            <a href="" data-ma-action="submenu-toggle"><i class="zmdi zmdi-layers"></i>Sales</a>
            <ul>
                <li class="{% if active_menu == 'election_create_open' %}active{% endif %} m-b-5">
                        <a class="pull-left p-r-0" title="Sales" href="#">Sales</a>
                        <a title="Create Sale " href="#">
                        <span class="pull-right glyphicon glyphicon-plus-sign"></span>
                        </a>
                    <div class="clearfix"></div>
                </li>
            </ul>
        </li>
    </ul>
</aside>

src/tutorial/templates/includes/not_found.html
<div class="card card-body card-padding">
	<div class="bg palette-Grey-100 m-b-0 p-20">Nothing found.</div>
</div>

src/tutorial/templates/includes/search.html
<div class="media-body h-search">
    	<form class="p-relative" action="" method="get">
        <input name="q" type="text" class="hs-input" placeholder="Search for customers">
        <i class="zmdi zmdi-search hs-reset" data-ma-action="search-clear"></i>
    </form>
</div>

src/tutorial/templates/includes/shortcuts.html
<div class="shortcuts">
	<button class="btn palette-Light-Blue btn-icon bg waves-effect waves-circle waves-float">
		<i class="zmdi zmdi-plus"></i>
	</button>
	<div class="icons icons text-right">
		
		<a href="#" class="btn btn-warning bg btn-icon-text waves-effect">Customers <i class="zmdi m-l-10 zmdi-accounts-alt"></i></a>
		
	</div>
</div>

src/tutorial/templates/includes/top_menu.html
{% load static %}

<ul class="pull-right h-menu">
            	
	<li class="hm-search-trigger">
	    <a href="" data-ma-action="search-open">
	        <i class="hm-icon zmdi zmdi-search"></i>
	    </a>
	</li>
	
	<li class="dropdown hidden-xs hidden-sm h-apps">
	    <a data-toggle="dropdown" href="">
	        <i class="hm-icon zmdi zmdi-apps"></i>
	    </a>
	    
	    <ul class="dropdown-menu pull-right">
			  <li>
			        <a href="#">
			            <i class="palette-Blue bg zmdi zmdi-view-list"></i>
			            <small>Customers</small>
			        </a>
			    </li>		    
		</ul>
	    
	</li>
	<li class="dropdown hidden-xs">
	    <a data-toggle="dropdown" href=""><i class="hm-icon zmdi zmdi-more-vert"></i></a>
	    <ul class="dropdown-menu dm-icon pull-right">
	        <li class="hidden-xs">
	            <a data-action="fullscreen" href=""><i class="zmdi zmdi-fullscreen"></i> Toggle Fullscreen</a>
	        </li>
	        <li>
	            <a href="#"><i class="zmdi zmdi-settings"></i> Settings</a>
	        </li>
	    </ul>
	</li>
	<li class="hm-alerts p-relative" data-user-alert="sua-messages" data-ma-action="sidebar-open" data-ma-target="user-alerts">
	    <a href=""><i class="hm-icon zmdi zmdi-notifications"></i><span class="notification-count palette-Red-500 bg">0</span></a>
	</li>
	<li class="dropdown hm-profile">
	    <a data-toggle="dropdown" href="">
	        <img src="{% static 'img/profile-pics/1.jpg' %}" alt="">
	    </a>
	    
	    <ul class="dropdown-menu pull-right dm-icon">
	        <!-- <li>
	            <a target="_blank" href="{% url 'auth_password_change' %}"><i class="zmdi zmdi-key"></i>Change Password</a>
	        </li> -->
	        <li>
	            <a href="{% url 'auth_logout' %}"><i class="zmdi zmdi-time-restore"></i> Logout</a>
	        </li>
	    </ul>
	</li>
	</ul>

src/tutorial/templates/includes/user_alerts.html
{% load static %}
<aside id="s-user-alerts" class="sidebar">
    <ul class="tab-nav tn-justified tn-icon m-t-10" data-tab-color="teal">
        <li><a class="sua-messages" href="#sua-messages" data-toggle="tab"><i class="zmdi zmdi-email"></i></a></li>
        <li><a class="sua-notifications" href="#sua-notifications" data-toggle="tab"><i class="zmdi zmdi-notifications"></i><span class="notification-count palette-Red-500 bg">{{recent_notifications.count}}</span></a></li>
        <li><a class="sua-tasks" href="#sua-tasks" data-toggle="tab"><i class="zmdi zmdi-view-list-alt"></i></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade" id="sua-messages">
            <ul class="sua-menu list-inline list-unstyled palette-Light-Blue bg">
                <li><a href="" data-ma-action="sidebar-close"><i class="zmdi zmdi-close"></i> Close</a></li>
            </ul>
			
			<div  class="list-group-item media">
				<div class="pull-left">
                    <i class="ic yellow zmdi zmdi-lamp"></i>
                </div>
                <div class="media-body">
                	<div class="lgi-heading">Coming Soon</div>
                    <small class="lgi-text">This feature not implemented yet. Will come soon.</small>
                </div>
            </div>
            
        </div>
        
        <div class="tab-pane fade" id="sua-notifications">
            <ul class="sua-menu list-inline list-unstyled palette-Orange bg">
                <li><a href="{% url 'users:notifications' %}"><i class="zmdi zmdi-long-arrow-tab"></i> View all</a></li>
                <li><a href="" data-ma-action="sidebar-close"><i class="zmdi zmdi-close"></i> Close</a></li>
            </ul>

            <div class="list-group lg-alt c-overflow">
            	{% if recent_notifications %}
            	{% for notification in recent_notifications %}
	            	{% if notification.subject.code == "low_stock_notification" %}
		                <div  class="list-group-item media">
		                    <div class="pull-left">
		                        <i class="ic red zmdi zmdi-alert-circle-o"></i>
		                    </div>
					
		                    <div class="media-body">
		                        <div class="lgi-heading">{{notification.subject}}</div>
		                        <small class="lgi-text">Only {{notification.product.stock}} item in stock of {{notification.product}} remaining ({{notification.product.shop}}).</small>
		                    </div>
		                </div>
	                {% endif %}
                    {% if notification.subject.code == "expiry_notification" %}
                            <div  class="list-group-item media">
                                <div class="pull-left">
                                    <i class="ic red zmdi zmdi-alert-circle-o"></i>
                                </div>
                        
                                <div class="media-body">
                                    <div class="lgi-heading">{{notification.subject}}</div>
                                    <small class="lgi-text">Hello Wrld</small>
                                </div>
                            </div>
                    {% endif %}
                    {% if notification.subject.code == "task_assigned" %}
                            <div  class="list-group-item media">
                                <div class="pull-left">
                                    <i class="ic red zmdi zmdi-alert-circle-o"></i>
                                </div>
                        
                                <div class="media-body">
                                    <div class="lgi-heading">{{notification.subject}}</div>
                                    <small class="lgi-text">New task</small>
                                </div>
                            </div>
                    {% endif %}
                {% endfor %}
                {% else %}
                <div  class="list-group-item media">
					<div class="pull-left">
	                    <i class="ic yellow zmdi zmdi-notifications-off"></i>
	                </div>
                    <div class="media-body">
                    	<div class="lgi-heading">No new notification(s)</div>
                        <small class="lgi-text">Currently you have no notification to show.</small>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        
        <div class="tab-pane fade" id="sua-tasks">
            <ul class="sua-menu list-inline list-unstyled palette-Green-400 bg">
                <li><a href="" data-ma-action="sidebar-close"><i class="zmdi zmdi-close"></i> Close</a></li>
            </ul>

            <div  class="list-group-item media">
				<div class="pull-left">
                    <i class="ic yellow zmdi zmdi-lamp"></i>
                </div>
                <div class="media-body">
                	<div class="lgi-heading">Coming Soon</div>
                    <small class="lgi-text">This feature not implemented yet. Will come soon.</small>
                </div>
            </div>
        </div>
    </div>
</aside>