src/tutorial/customers/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^$', views.customers, name='customers'),
    url(r'^edit/(?P<pk>.*)$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>.*)$', views.delete, name='delete'),
    url(r'^view/(?P<pk>.*)$', views.customer, name='customer'),
]

src/tutorial/sales/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^$', views.sales, name='sales'),
    url(r'^edit/(?P<pk>.*)$', views.edit, name='edit'),
    url(r'^delete/(?P<pk>.*)$', views.delete, name='delete'),
    url(r'^view/(?P<pk>.*)$', views.sale, name='sale'),
]

src/tutorial/tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),

    url(r'^app/products/', include('products.urls', namespace="products")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")),
    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/users/', include('users.urls', namespace="users")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

src/tutorial/customers/models.py
from __future__ import unicode_literals
from django.db import models
from main.models import BaseModel
from django.utils.translation import ugettext_lazy as _


class Customer(BaseModel):
    name = models.CharField(max_length = 120)
    phone = models.CharField(max_length = 12)
    email = models.EmailField()
    address = models.TextField()

    class Meta:
        db_table = 'customers_customer'
        verbose_name = _('customer')
        verbose_name_plural = _('customers')
        ordering = ('-date_added','name')

    def __unicode__(self):
        return str(self.name)

src/tutorial/customers/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms.widgets import TextInput, Textarea
from customers.models import Customer

class CustomerForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        exclude = ['creator','updator','auto_id','is_deleted']
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Name'}),
            'email': TextInput(attrs={'class': 'required email form-control','placeholder' : 'Email'}),
            'phone': TextInput(attrs={'class': 'required form-control','placeholder' : 'Phone'}),
            'address': Textarea(attrs={'class': 'required form-control','placeholder' : 'Address'}),
        }
        error_messages = {
            'name' : {
                'required' : _("Name field is required."),
            },
            'email' : {
                'required' : _("Email field is required."),
            },
            'phone' : {
                'required' : _("Phone field is required."),
            },
            'address' : {
                'required' : _("Address field is required."),
            },
        }

src/tutorial/customers/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from main.decorators import check_mode, ajax_required
from main.functions import get_auto_id, generate_form_errors, get_a_id
import json
from django.views.decorators.http import require_GET
from users.models import NotificationSubject, Notification
from django.db.models import Sum
from django.contrib.auth.models import Group
import datetime
from calendar import monthrange
from django.utils import timezone
from decimal import Decimal
from customers.models import Customer
from customers.forms import CustomerForm


def create(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            data = form.save(commit = False)
            # curent user
            data.creator = request.user 
            data.updator = request.user 
            data.auto_id = get_auto_id(Customer)
            data.save()

            response_data = {
                'status' : 'true',
                'title' : 'succesfully submitted',
                'message' : 'registration completed succesfully',
                'redirect' : 'true',
                'redirect_url' : reverse('customers:customer',kwargs = {"pk" :data.pk}) 
            }

        else:
            message = generate_form_errors(form,formset=False)

            response_data = {
                'status' : 'false',
                'stable' : 'true',
                'title' : 'form validation error',
                'message' : message,
            }

        return HttpResponse(json.dumps(response_data),content_type = 'application/javascript')
    else:
        form = CustomerForm()
        context = {
            "form" : form,
            "title" : "create customer",
            "redirect" : True,

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,

        }

        return render(request,'customers/entry.html',context)


def customers(request):
    instances = Customer.objects.filter(is_deleted = False)
    context = {
        "title" : "Customers",
        "instances" : instances,

        "is_need_select_picker" : True,
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_wave_effect" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_chosen_select" : True,
        "is_need_grid_system" : True,
        "is_need_datetime_picker" : True,
        "is_need_animations": True,
    }

    return render(request, "customers/customers.html" ,context)


def edit(request,pk):
    instance = get_object_or_404(Customer.objects.filter(pk = pk))
    if request.method == "POST":
        form = CustomerForm(request.POST,instance = instance)
        if form.is_valid():
            data = form.save(commit = False)
            data.date_updated = datetime.datetime.now()
            data.updator = request.user 
            data.auto_id = get_auto_id(Customer)
            data.save()

            response_data = {
                'status' : 'true',
                'title' : 'succesfully Updated',
                'message' : 'registration completed succesfully',
                'redirect' : 'true',
                'redirect_url' : reverse('customers:customer',kwargs = {"pk" :data.pk}) 
            }

        else:
            message = generate_form_errors(form,formset=False)

            response_data = {
                'status' : 'false',
                'stable' : 'true',
                'title' : 'form validation error',
                'message' : message,
            }

        return HttpResponse(json.dumps(response_data),content_type = 'application/javascript')
    else:
        form = CustomerForm(instance = instance)
        context = {
            "form" : form,
            "title" : "create customer",
            "redirect" : True,

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,

        }

        return render(request,'customers/entry.html',context)


def delete(request,pk):
    Customer.objects.filter(pk=pk).update(is_deleted=True)

    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Customer Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('customers:customers')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


def customer(request,pk):
    instance = get_object_or_404(Customer.objects.filter(pk = pk))
    context = {
        "title" : "Customer "+instance.name,
        "instance" : instance,

        "is_need_select_picker" : True,
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_wave_effect" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_chosen_select" : True,
        "is_need_grid_system" : True,
        "is_need_datetime_picker" : True,
        "is_need_animations": True,
    }

    return render(request, "customers/customer.html" ,context)

src/tutorial/templates/customers/customer.html
{% extends "base.html" %}
{% load i18n %}

{% load users_template_tags %}
{% load tz %}
{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{instance.name}} - {{instance.phone}}</div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a title="Create Customer" href="{% url 'customers:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Edit Customer" href="{% url 'customers:edit' pk=instance.pk %}">
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete Customer" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'customers:delete' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div id="c-grid" class="clearfix" data-columns="2">
                <div class="card">
                    <div class="card-header">
                        <h2>Basic Info <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Name</div>
                                    <small class="lgi-text">{{instance.name}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Phone</div>
                                    <small class="lgi-text">{{instance.phone}}</small>
                                </div>
                            </div>
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Email</div>
                                    <small class="lgi-text">{{instance.email}}</small>
                                </div>
                            </div>
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Address</div>
                                    <small class="lgi-text">{{instance.address}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

src/tutorial/templates/customers/customers.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
             <div class="c-header">
            	<h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
	            <div class="ah-label hidden-xs palette-White text">{{title}}</div>

	            <div class="ah-search">
	            	<form method="get" action="{% url 'customers:customers' %}" class="ahs-input">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>

	            <ul class="ah-actions actions a-alt">
	                <li>
	                    <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
	                        <i class="zmdi zmdi-search"></i>
	                    </a>
	                </li>
	                <li>
	                    <a title="Filter" class="filter_button" href="">
	                        <i class="zmdi zmdi-filter-list"></i>
	                    </a>
	                </li>
	                <li>
                        <a title="Create Customer" href="{% url 'customers:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
	                {% if instances %}
    	                <li>
    	                    <a title="Select All" class="check_all" href="">
    	                        <i class="zmdi zmdi-select-all"></i>
    	                    </a>
    	                </li>
	                {% endif %}
	            </ul>
	        </div>

            <div class="card">

				{% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                            	<th style="width:20px;"></th>
                                <th data-column-id="id" data-type="numeric">ID</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>E-mail</th>
                                <th>Address</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% load el_pagination_tags %}
							{% paginate 21 instances %}
                        	{% for instance in instances %}
                            <tr class="check_items_row">
                            	<td style="width:20px;">
                            		<div class="checkbox lgi-checkbox m-t-5">
			                            <label>
			                                <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
			                                <i class="input-helper"></i>
			                            </label>
			                        </div>
                            	</td>
                                <td><a href="{% url 'customers:customer' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                <td>{{instance.name}}</td>
                                <td>{{instance.phone}}</td>
                                <td>{{instance.email}}</td>
                                <td>{{instance.address}}</td>
                                <td>
                                	<a href="{% url 'customers:customer' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                	<a href="{% url 'customers:edit' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                	<a data-id="{{instance.pk}}" href="{% url 'customers:delete' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                	{% get_pages %}
                	<div class="row">
                		<div class="col-sm-6">
                			<div class="pagination">
                				{% show_pages %}
                			</div>
                		</div>
                		<div class="col-sm-6 infoBar">
                			<div class="infos">
                				Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                			</div>
                		</div>
                	</div>
                </div>
                <!--pagination-->
                {% else %}
                	{% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
	 <form method="get" action="{% url 'customers:customers' %}">
	 	<div class="card">
			<div class="card-header">
		        <h2>Filter <small></small></h2>
		        <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
		    </div>

			<div class="card-body card-padding">
			 	<div class="form-group fg-line">
		            <label>Query</label>
		            <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
		        </div>

		         <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
		    </div>
		 </div>
	 </form>
</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

src/tutorial/templates/customers/entry.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<section id="content">
    <div class="container">
        <div class="c-header">
            <h2>{{title}}</h2>
        </div>
        <div class="action-header palette-theme {{current_theme}} bg clearfix">
            <div class="ah-label hidden-xs palette-White text">{{title}}</div>
            <div class="ah-search">
                <form method="get" action="{% url 'customers:customers' %}">
                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                    <input type="submit" class="hidden" />
                </form>
            </div>
            <ul class="ah-actions actions a-alt">
                <li>
                    <a title="Search" data-ma-action="ah-search-open" class="ah-search-trigger" href="">
                    <i class="zmdi zmdi-search"></i>
                    </a>
                </li>
                {% if instance %}
                <li>
                    <a title="Create Customer" href="{% url 'customers:create' %}">
                    <i class="zmdi zmdi-plus"></i>
                    </a>
                </li>
                <li>
                    <a title="View Customer" href="{% url 'customers:customer' pk=instance.pk %}">
                    <i class="zmdi zmdi-eye"></i>
                    </a>
                </li>
                <li>
                    <a title="Delete Customer" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'customers:delete' pk=instance.pk %}" class="action-button redirect">
                    <i class="zmdi zmdi-delete"></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="card">
            <form class="ajax reset {% if redirect %}redirect{% endif %}" method="post" action="{{url}}">
                {% csrf_token %}
                <div class="card-body card-padding">
                    <div class="row">
                        <div class="col-sm-6">
                            {{ form.customers }}
                            <div class="form-group fg-line">
                                <label for="{{ form.name.id_for_label }}">
                                {{ form.name.label }}
                                {% if form.name.field.required %}
                                <small class="star">*</small>
                                {% endif %}
                                {% if form.name.help_text %}
                                <span data-original-title="Field Info" title="" data-content="{{ form.name.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                {% endif %}
                                </label>
                                {{ form.name }}
                                {% if form.name.errors %}
                                <label class="error">{{ form.name.errors.as_text }}</label>
                                {% endif %}
                            </div>
                            <div class="form-group fg-line">
                                <label for="{{ form.name.id_for_label }}">
                                {{ form.email.label }}
                                {% if form.email.field.required %}
                                <small class="star">*</small>
                                {% endif %}
                                {% if form.email.help_text %}
                                <span data-original-title="Field Info" title="" data-content="{{ form.email.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                {% endif %}
                                </label>
                                {{ form.email }}
                                {% if form.email.errors %}
                                <label class="error">{{ form.email.errors.as_text }}</label>
                                {% endif %}
                            </div>
                            <div class="form-group fg-line m-b-0">
                                <label for="{{ form.phone.id_for_label }}">
                                {{ form.phone.label }}
                                {% if form.phone.field.required %}
                                <small class="star">*</small>
                                {% endif %}
                                {% if form.phone.help_text %}
                                <span data-original-title="Field Info" title="" data-content="{{ form.phone.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                {% endif %}
                                </label>
                                {{ form.phone }}
                                {% if form.phone.errors %}
                                <label class="error">{{ form.phone.errors.as_text }}</label>
                                {% endif %}
                            </div>
                            <div class="form-group fg-line">
                                <label for="{{ form.name.id_for_label }}">
                                {{ form.address.label }}
                                {% if form.address.field.required %}
                                <small class="star">*</small>
                                {% endif %}
                                {% if form.address.help_text %}
                                <span data-original-title="Field Info" title="" data-content="{{ form.address.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                {% endif %}
                                </label>
                                {{ form.address }}
                                {% if form.address.errors %}
                                <label class="error">{{ form.address.errors.as_text }}</label>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="m-t-20">
                        <button type="submit" class="btn btn-info waves-effect">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block static %}
{% load static %}
<script type="text/javascript">
    $(document).ready(function(){
        $('input[type=text]').focus(function () {
           $(this).select();
            });
      });
</script>
{% endblock %}